reporting_points:
    input: 
        CSV: ../data/reporting_points/Station-2022-10-27v12.csv
        GIS: ../data/GIS/fixed_report_points_500.shp
        rivers: ../data/GIS/RiversForWebPage_EU_ready.shp
    area: 500 # minimum catchment area (km²)
    catchments: # catchments on which the skill analysis will focus
    selection:
        rho: 0.9 # the maximum correlation coefficient allowed between 2 reporting points
    output: ../results/reporting_points/
    
discharge:
    input:
        reanalysis: E:/casadje/Documents/skill_assessment/data/CDS/reanalysis/
        forecast: E:/casadje/Documents/skill_assessment/data/CDS/forecast/
    study_period:
        start: 2021-01-01 # start date of the analysis (e.g. 2020-01-01)
        end: 2022-12-31 18:00 # end date of the analysis (e.g. 2022-12-31)
    return_period:
        input: ../data/thresholds/return_levels.nc
        threshold: 5    # years
        reducing_factor: 0.05 # None
    output:
        reanalysis: ../data/discharge/reanalysis/
            
exceedance:
    output:
        reanalysis: ../results/exceedance/reanalysis/
        forecast: ../results/exceedance/forecast/

hits:
    criteria:
        probability: [0.05, 0.96, 0.025] # minimum, maximum and step values
        persistence: [[1, 1], [2, 4], [2, 3], [2, 2], [3, 4], [3, 3]]
    window: 5    # width of the rolling window used to compute hits (no. of timesteps) to allow for a time shift between forecast and observation
    center: True # whether the previous rolling window is centered or not
    seasonality: False
    output: ../results/hits/
    
skill:
    current_criteria:
        approach: 1_deterministic_+_1_probabilistic
        probability: 0.3
        persistence: 3/3
    leadtime: 60 # minimum leadtime (in hours) for which the notification criteria will be optimized
    area: 2000   # minimum catchment area (in km²) for which the notification criteria will be optimized
    beta: 1   # coefficient of the fbeta-score (by default is 1)
    optimization:
        kfold: 10 # number of splits in the cross-validation optimization. If None, cross-validation will not be applied
        train_size: 0.707 # proportion of the complete set of reporting points in each cross-validation subset
        tolerance: 0.01 # criteria with a skill difference lower than this value will be considered equally-performing
        minimize_spread: # whether to minimize the difference between precision and recall among criteria performing similarly in terms of fscore
            probability: False
            persistence: False
    output: ../results/skill/
    
