reporting_points:
    input: 
        CSV: ../data/reporting_points/Station-2022-10-27v12_KGE.csv                # table of fixed reporting points
        GIS: ../data/GIS/fixed_report_points_500.shp                           # shapefile of fixed reporting points used to correct river and catchment names, and add the Pfafstetter code
    rivers: ../data/GIS/rivers_europe.shp                      # optional shapefile of rivers. Only used for plots
    area: 500                                                                  # minimum catchment area (km²)
    catchments:                                                                # catchments on which the skill analysis will focus
    KGE: 0.5                                                                       # minimum values of KGE that a reporting point must meet to be included in the skill assessment
    selection:
        rho: 0.9                                                               # the maximum correlation coefficient allowed between 2 reporting points
        upstream: True                                                         # whether to give priority to stations upstream (True) or downstream (False) reporting points
    output: ../results/reporting_points/                                       # directory where the output table of reporting points will be saved
    
discharge:
    input:
        reanalysis: E:/casadje/Documents/EFASv4/reanalysis/                    # directory were the original reanalysis discharge files are stored
        forecast: E:/casadje/Documents/EFASv4/forecast/                        # directory were the original forecast discharge files are stored
    study_period:
        start: 2020-10-24 06:00                                                 # start date of the analysis (e.g. 2020-01-01)
        end: 2023-06-30 18:00                                                   # end date of the analysis (e.g. 2022-12-31 18:00 )
    return_period:
        input: ../data/thresholds/return_levels.nc                              # NetCDF file with the return periods of discharge
        threshold: 5                                                            # return period whose exceedance is considered a flood event
        reducing_factor: 0.05                                                   # factor reducing the discharge associated to the previous return period (not necessary)
    output:
        reanalysis: ../data/discharge/reanalysis/                               # directory where the preprocessed reanalysis discharge will be saved
            
exceedance:
    output:
        reanalysis: ../results/exceedance/reanalysis/                           # directory where the reanalysis exceedance probability will be saved
        forecast: ../results/exceedance/forecast/                               # directory where the forecast exceedance probability will be saved

hits:
    criteria:
        probability: [0.05, 0.96, 0.025]                                        # search values of the probability criterion: minimum, maximum and step
        persistence: [[1, 1], [2, 4], [2, 3], [2, 2], [3, 4], [3, 3]]           # search values for the persistence criterion
    leadtime:                                                                   # integer or list of lead times between which hits will be computed
    window: 1                                                                   # width of the rolling window used to compute hits (no. of timesteps) to allow for a time shift between forecast and observation
    center: True                                                                # whether the previous rolling window is centered or not
    seasonality: False                                                          # whether to split the analysis in seasons or not
    output: ../results/hits/2020_2023/                                          # directory where the NetCDF files of hits/misses/false alarms will be stored
    
skill:
    current_criteria:                                                           # benchmark criteria
        approach: 1_deterministic_+_1_probabilistic
        probability: 0.3
        persistence: 3/3
    leadtime: 60 #                                                              # minimum/maximum leadtime (hours) for which the notification criteria will be optimized
    area: 2000                                                                  # minimum/maximum catchment area (km²) for which the notification criteria will be optimized
    beta: 0.8                                                                   # coefficient of the fbeta-score (by default is 1)
    optimization:
        kfold: 10                                                               # number of splits in the cross-validation optimization. If None, cross-validation will not be applied
        train_size: 0.707                                                       # proportion of the complete set of reporting points in each cross-validation subset
        stratify: False                                                         # whether the sampling should be done randomly (False) or based on the number of "observed" events (True)
        tolerance: 0.001                                                         # criteria with a skill difference lower than this value will be considered equally-performing
        minimize_spread:                                                        # whether to minimize the difference between precision and recall among criteria performing similarly in terms of fscore
            probability: False
            persistence: False
    output: ../results/skill/2020_2023/                                                   # directory where results will be saved
    
