reporting_points:
    input: 
        CSV: ../data/reporting_points/Station-2022-10-27v12_KGE.csv
        GIS: ../data/GIS/fixed_report_points_500.shp
    rivers: ../data/GIS/rivers_europe.shp
    area: 500
    catchments:
    KGE: 0.5
    selection:
        rho: 0.9
        upstream: True
    output: ../results/reporting_points/
    
discharge:
    input:
        reanalysis: E:/casadje/Documents/EFASv4/reanalysis/
        forecast: E:/casadje/Documents/EFASv4/forecast/
    study_period:
        start: 2020-10-24 06:00
        end: 2023-06-30 18:00
    return_period:
        input: ../data/thresholds/return_levels.nc
        threshold: 5
        reducing_factor: 0.05
    output:
        reanalysis: ../data/discharge/reanalysis/
            
exceedance:
    output:
        reanalysis: ../results/exceedance/reanalysis/
        forecast: ../results/exceedance/forecast/

hits:
    experiment: NWP
    criteria:
        probability: [0.05, 0.96, 0.025]
        persistence: [[1, 1], [2, 4], [2, 3], [2, 2], [3, 4], [3, 3]]
    leadtime: [0, 24, 48, 72, 96, 120, 144, 168, 192, 216] 
    window: 1
    center: True
    output: ../results/hits/
    
skill:
    current_criteria:
        approach: 1_deterministic_+_1_probabilistic
        probability: 0.3
        persistence: 3/3
    leadtime: 60
    area: 2000
    beta: 1
    optimization:
        kfold: 10
        train_size: 0.707
        stratify: False
        tolerance: 0.001
        minimize_spread:
            probability: False
            persistence: False
    output: ../results/skill/